import type { Product } from "./types";

// Development-only fallback used when VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY
// are not set. Mirrors the current Vault so the public site keeps working locally.
// Do not edit this in production — once Supabase is wired up, the live source of
// truth is the `products` table.

const now = "2026-05-29T00:00:00.000Z";

export const localProducts: Product[] = [
  {
    id: "local-1",
    title: "Oracle Prompt Vault",
    category: "Prompts",
    description: "200+ premium AI prompts for brand, content, and strategy.",
    price: "$47",
    ctaLabel: "View Product",
    featured: true,
    status: "active",
    image: null,
    slug: "oracle-prompt-vault",
    stripePaymentLink: null,
    isPaidProduct: true,
    deliveryType: "download",
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "local-2",
    title: "AI Brand Weaver Kit",
    category: "Branding",
    description: "Brand voice, identity, and positioning playbook.",
    price: "$97",
    ctaLabel: "View Product",
    featured: false,
    status: "active",
    image: null,
    slug: "ai-brand-weaver-kit",
    stripePaymentLink: null,
    isPaidProduct: true,
    deliveryType: "download",
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "local-3",
    title: "Crimson Content System",
    category: "Content",
    description: "A weekly content engine powered by AI and intention.",
    price: "$67",
    ctaLabel: "View Product",
    featured: false,
    status: "active",
    image: null,
    slug: "crimson-content-system",
    stripePaymentLink: null,
    isPaidProduct: true,
    deliveryType: "download",
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "local-4",
    title: "Website Audit Blueprint",
    category: "Strategy",
    description: "Diagnose, refine, and elevate your digital presence.",
    price: "$37",
    ctaLabel: "View Product",
    featured: false,
    status: "active",
    image: null,
    slug: "website-audit-blueprint",
    stripePaymentLink: null,
    isPaidProduct: true,
    deliveryType: "download",
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "local-5",
    title: "Digital Product Starter Kit",
    category: "Systems",
    description: "Launch your first digital product in seven days.",
    price: "$57",
    ctaLabel: "View Product",
    featured: false,
    status: "active",
    image: null,
    slug: "digital-product-starter-kit",
    stripePaymentLink: null,
    isPaidProduct: true,
    deliveryType: "download",
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "local-6",
    title: "Canva Marketing Templates",
    category: "Design",
    description: "120 luxe templates for socials, lead magnets, and decks.",
    price: "$29",
    ctaLabel: "View Product",
    featured: false,
    status: "active",
    image: null,
    slug: "canva-marketing-templates",
    stripePaymentLink: null,
    isPaidProduct: true,
    deliveryType: "download",
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
];
