/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyVaultRouteImport } from './routes/my-vault'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultSlugRouteImport } from './routes/vault/$slug'
import { Route as StudioWebsiteAuditBlueprintRouteImport } from './routes/studio/website-audit-blueprint'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const MyVaultRoute = MyVaultRouteImport.update({
  id: '/my-vault',
  path: '/my-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultSlugRoute = VaultSlugRouteImport.update({
  id: '/vault/$slug',
  path: '/vault/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioWebsiteAuditBlueprintRoute =
  StudioWebsiteAuditBlueprintRouteImport.update({
    id: '/studio/website-audit-blueprint',
    path: '/studio/website-audit-blueprint',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-vault': typeof MyVaultRoute
  '/account/login': typeof AccountLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/studio/website-audit-blueprint': typeof StudioWebsiteAuditBlueprintRoute
  '/vault/$slug': typeof VaultSlugRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-vault': typeof MyVaultRoute
  '/account/login': typeof AccountLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/studio/website-audit-blueprint': typeof StudioWebsiteAuditBlueprintRoute
  '/vault/$slug': typeof VaultSlugRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-vault': typeof MyVaultRoute
  '/account/login': typeof AccountLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/studio/website-audit-blueprint': typeof StudioWebsiteAuditBlueprintRoute
  '/vault/$slug': typeof VaultSlugRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-vault'
    | '/account/login'
    | '/admin/products'
    | '/api/checkout'
    | '/studio/website-audit-blueprint'
    | '/vault/$slug'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-vault'
    | '/account/login'
    | '/admin/products'
    | '/api/checkout'
    | '/studio/website-audit-blueprint'
    | '/vault/$slug'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/my-vault'
    | '/account/login'
    | '/admin/products'
    | '/api/checkout'
    | '/studio/website-audit-blueprint'
    | '/vault/$slug'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyVaultRoute: typeof MyVaultRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AdminProductsRoute: typeof AdminProductsRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  StudioWebsiteAuditBlueprintRoute: typeof StudioWebsiteAuditBlueprintRoute
  VaultSlugRoute: typeof VaultSlugRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-vault': {
      id: '/my-vault'
      path: '/my-vault'
      fullPath: '/my-vault'
      preLoaderRoute: typeof MyVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$slug': {
      id: '/vault/$slug'
      path: '/vault/$slug'
      fullPath: '/vault/$slug'
      preLoaderRoute: typeof VaultSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/website-audit-blueprint': {
      id: '/studio/website-audit-blueprint'
      path: '/studio/website-audit-blueprint'
      fullPath: '/studio/website-audit-blueprint'
      preLoaderRoute: typeof StudioWebsiteAuditBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyVaultRoute: MyVaultRoute,
  AccountLoginRoute: AccountLoginRoute,
  AdminProductsRoute: AdminProductsRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  StudioWebsiteAuditBlueprintRoute: StudioWebsiteAuditBlueprintRoute,
  VaultSlugRoute: VaultSlugRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
